services:

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./db:/data/db
    networks:
      - app-network

  client:
    container_name: client
    restart: always
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - app-network

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge